name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print pre cache
        run: |
          echo Version
          cat version
          echo
          echo Files in root
          ls -la
          echo
          echo Files in cache
          ls -la .yarn/cache
          echo
          echo Files in .yarn
          ls -la .yarn/
          echo
          echo Files in .devops
          ls -la .devops

      - name: Restore from cache
        uses: actions/cache/restore@v4
        id: load-cache
        with:
          path: |
            .yarn/**
            node_modules/**
          key: ${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Print post cache
        run: |
          echo Version
          cat version
          echo
          echo Files in root
          ls -la
          echo
          echo Files in cache
          ls -la .yarn/cache
          echo
          echo Files in .yarn
          ls -la .yarn/
          echo
          echo Files in .devops
          ls -la .devops
        
      - name: Gen random
        run: |
          NUM=$(node rand.js)
          echo NUM=$NUM
          touch .yarn/cache/$NUM
          echo $NUM >> .yarn/install-state.gz
          echo $NUM >> .devops/somefile

      - name: Print post random
        run: |
          echo Version
          cat version
          echo
          echo Files in root
          ls -la
          echo
          echo Files in cache
          ls -la .yarn/cache
          echo
          echo Files in .yarn
          ls -la .yarn/
          echo
          echo Files in .devops
          ls -la .devops

      - name: Save cache
        uses: actions/cache/save@v4
        if: steps.load-cache.outputs.cache-hit != 'true'
        id: save-cache
        with:
          path: |
            .yarn/**
            node_modules/**
          key: ${{ steps.load-cache.outputs.cache-primary-key }}          
  