name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print pre cache
        run: |
          echo Files in root
          ls -la
          echo
          echo Files in cache
          ls -la cache

      - name: Restore from cache
        uses: actions/cache/restore@v4
        id: load-cache
        with:
            path: cache/**
            key: ${{ runner.os }}-${{ github.run_id }}
            restore-keys: |
              ${{ runner.os }}-

      - name: Print post cache
        run: |
          echo Files in root
          ls -la
          echo
          echo Files in cache
          ls -la cache
        
      - name: Gen random
        run: |
          NUM=$(node rand.js)
          echo NUM=$NUM
          touch cache/$NUM

      - name: Print post random
        run: |
          echo Files in root
          ls -la
          echo
          echo Files in cache
          ls -la cache

      - name: Save cache
        uses: actions/cache/save@v4
        if: steps.load-cache.outputs.cache-hit != 'true'
        id: save-cache
        with:
            path: cache/**
            key: ${{ steps.load-cache.outputs.cache-primary-key }}          
  